### ISSUE TITLE
VimCompleteEnable only enables completion for current buffer

### ISSUE THREAD

**Issue by EgZvor** [girishji/vimcomplete#1]
I was wondering why completion wouldn't work for me and it turns out that VimCompleteEnable only enables completion for a single buffer. Not sure if it's intentional but using

```vim
autocmd VimEnter * VimCompleteEnable
```

does not work then.

Edit: using

```vim
autocmd BufRead * VimCompleteEnable
```

works fine

**Comment by girishji** [comment]
Thanks. The doc is not correct. I will update the doc to reflect correct way of initialization. Since the plugin works per buffer, it has to be enabled every time a new buffer is read so it sets up correct completion sources.
