### ISSUE TITLE
Using LSP and `compile_commands.json` - Example Configuration

### ISSUE THREAD

**Issue by xave** [girishji/vimcomplete#12]
I am looking for a sample configuration for my .vimrc. 

In order to get the LSP working, I have already had to generate a `compile_commands.json`. Ideally, the autocomplete could be configured to look there. I see that there are many options on the main page, but I am not sure how to use them syntactically in a vimrc.

My vim stack is:

`ale`
`vim-lsp`
`vim-lsp-ale`
`clang compiler` and its `compile_commands.json`
`vim 9` on `macOS`

I am thinking I would want some sort of precedence (highest to lowest):
1. compile_commands.json
2. buffer
3. ...
4. resorting to searching headers dead last as it takes a lot of time

I typically use ctags as well, though I could write something that uses both.

**Comment by girishji** [comment]
Is this a clangd setup or LSP client setup configuration question? If so https://github.com/yegappan/lsp is a better place to ask. There is a wiki on that project that shows how to setup.

It is not clear to me if compile_commands.json should be used as a source of autocompletion. From what I understand, clangd can be made to look for the build database json file to figure out the context and emit appropriate completion items, which this plugin uses (through LSP client). LSP client (https://github.com/yegappan/lsp) should be setup first before using this plugin.

**Comment by xave** [comment]
Thank you for your response.  I ended up getting things to work with a different set of plugins. `vim-lsp` and `asyncomplete`. Both use the `compile_commands.json` database to both power the LSP and the autocomplete.
