### ISSUE TITLE
Cant popup dictionary words when dictionary.timeout > 0

### ISSUE THREAD

**Issue by Angluca** [girishji/vimcomplete#13]
It's very laggy when you hold key down in MacVim, So want dictionary.timout = 100, But can't use T_T now version

**Comment by girishji** [comment]
`timeout` is not implemented for dictionary yet, as the document says. It is on the TODO list. How big is your dictionary? I am thinking of implementing Aho-Korasick algorithm for fast searches.

**Comment by girishji** [comment]
Can you try by setting `sortedDict = false` and `onlyWords = false`?

If your dictionary contains characters like `(`, '[`', etc. the regex matching will slow down. I can improve this if you provide me your dictionary file.

**Comment by girishji** [comment]
I fixed a few issues. Please upgrade and let me know if you still have problems.

You can set options as follows:
```
    var dictproperties = {
        zig: {sortedDict: true, onlyWords: false }
    }
    g:VimCompleteOptionsSet({
        dictionary: { enable: true, priority: 10, maxCount: 100, filetypes: ['zig'], properties: dictproperties },
})
```

**Comment by girishji** [comment]
Thanks, fixed.
