### ISSUE TITLE
OmniFunc-related error

### ISSUE THREAD

**Issue by riskygit** [girishji/vimcomplete#14]
I may have misconfigured something, but I have the `nil` language server for nix running... editing the buffer seems to cause this error for every key entered.

```
Error detected while processing function <SNR>14_AsyncGetItems[21]..<SNR>14_GetItems[6]..lsp#Completor[20]..LspOmniFunc:
line   46:
E716: Key not present in Dictionary: "completeItemsIsIncomplete"
Press ENTER or type command to continue
```

```vim
packadd lsp
packadd vimcomplete

g:LspOptionsSet({
  completionMatcher: 'icase',
  diagVirtualTextAlign: 'after',
  ignoreMissingServer: true,
  noNewlineInCompletion: true,
  showInlayHints: true,
})

g:LspAddServer([{
  name: 'nil',
  filetype: ['nix'],
  path: 'nil',
  args: [],
  rootSearch: ['flake.nix', '.git'],
  workspaceConfig: {
    nil: {
      formatting: {
        command: [ "nixpkgs-fmt" ]
      },
      nix: {
        flake: {
          autoArchive: false,
        },
      },
    }
  },
}])

g:VimCompleteOptionsSet({
  completor: {
    noNewlineInCompletion: true,
    #recency: false,
  },
  lsp: {
    enable: true,
    priority: 20,
  },
  vimscript: {
    enable: true,
    priority: 15,
  },
})
```

Additionally, I've noticed hitting enter in a completion popup still enters a new line despite `noNewlineInCompletion: true` for both the LSP and the completion plugin.

**Comment by girishji** [comment]
First error is coming from yegappan LSP client (file completion.vim, line 517). I am familiar with that plugin. I will look into both issues.

**Comment by girishji** [comment]
I could not reproduce either of your problems. I do not have nixos server though. I just tried it without `nil` server on file with `.nix` extension. Can you upgrade everything and check if you get the same problem with any other LSP? 

For the second problem, what do you see for `<cr>` when you do `:map`. Can you do  `:iunmap <expr> <buffer> <CR>` and check if it makes any difference?

**Comment by riskygit** [comment]
I recorded my screen showing:
1. <cr> is not mapped
2. the error that appears when typing
3. new lines inserted when hitting enter in the popup

https://github.com/girishji/vimcomplete/assets/105889909/dd3904e6-1704-49dd-aade-1ee2e8ec9026

**Comment by girishji** [comment]
I could not reproduce the error when typing. I used the following config. I inspected the code in LSP client and I do not see the possibility, unless the first call to LspOmnifunc() is not getting called. I need more info. Do you have the latest version of all plugins? I would debug this if I can reproduce it.

```
g:LspAddServer([{
        name: 'rustanalyzer',
        filetype: ['rust'],
        path: 'rust-analyzer-aarch64-apple-darwin',
        args: [],
        syncInit: v:true
    }])
```
Regarding the second problem, it is working as expected. It will not insert `<cr>` when **no item is selected** in the menu. This is the Vim behavior when you `set completeopt=menuone,popup,noinsert,noselect`. You could use `menu` instead of `menuone` and it will be the same.

**Comment by riskygit** [comment]
Okay I understand the newline bit. On the other issue, everything is definitely up to date. I've tried changing configuration settings, but I'm not sure what is causing this. Is there a way I can output more information about the error? I am not sure how to print additional details.

**Comment by Sharpeee** [comment]
I also get this error from time to time. Sometimes it helps to restart vim, other times I have to live with it until, I am done editing that particular line (it only happens on certain lines of code, sometimes).

For reference, I am using '[jedi-language-server](https://github.com/pappasam/jedi-language-server)' as LSP server.

**Comment by Sharpeee** [comment]
I just tried a minor fix in yegappans lsp, but I have a really hard time reproducing this, so I do not know if it actually works. @riskygit could you try this change?

Change line 517 in `lsp/autoload/lsp/completion.vim` to
```
if prefix->empty() || lspserver->get('completeItemsIsIncomplete', false)
```

**Comment by girishji** [comment]
I reproduced the problem. It happens when I use packadd. The bug is in LSP client. It is not setting completeItemsIsIncomplete to false when the items list returned by LSP server is empty. I will submit a PR soon. I will have to figure out why it didn't happen when I used Plug.

**Comment by girishji** [comment]
This should fix:
https://github.com/yegappan/lsp/pull/450
