### ISSUE TITLE
How to sort dict use vim?

### ISSUE THREAD

**Issue by Angluca** [girishji/vimcomplete#16]
I use vim :sort command sort this dict, But It can't even find the right word by capitalizing the first letter. ( Inputting "This" word can't prompt correctly)
https://github.com/Angluca/AcVim/blob/master/vimfiles/dict/zig.dict

**Comment by girishji** [comment]
I can find 'This':

<img width="228" alt="Screenshot 2024-02-06 at 2 03 22 PM" src="https://github.com/girishji/vimcomplete/assets/16529248/dfe2c621-6e4c-451b-a379-6837dfa20aab">

**Comment by girishji** [comment]
Let me look.

**Comment by girishji** [comment]
I fixed the problem. I had intentionally limited to one dictionary in the previous design, but those constraints are no longer applicable.
