### ISSUE TITLE
Completion kind support (with yegappan’s LSP)

### ISSUE THREAD

**Issue by riskygit** [girishji/vimcomplete#17]
Is it possible to show an indication of what the completion kind from the LSP is? Function, variable, method, keyword, etc. Without vimcomplete, the LSP supports this information, but vimcomplete disables it in lsp.vim. I think there's a highlight group for "extra information" PmenuExtra(Sel) that might refer to an area that could be used?

**Comment by girishji** [comment]
Done. You can hide them (see options).
