### ISSUE TITLE
Please do not add `/` to a directory name in path completion

### ISSUE THREAD

**Issue by beavailable** [girishji/vimcomplete#18]
Just like the way [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim) do, or give users an option to configure, because there are two reasons:
- Sometimes I just don't want the `/` after a file path.
- if I forget the name of a subdirectory or a file of the `~/foo` directory, I can just type `/` to trigger the completion, when I select a subdirectory or file named `bar`, I get `~/foo/bar` instead of `~/foo//bar`.

Thanks a lot.

**Comment by girishji** [comment]
Seems like a good idea. Done.
