### ISSUE TITLE
vimcomplete does not allow tab completion

### ISSUE THREAD

**Issue by boput** [girishji/vimcomplete#2]
Hi, I am using latest Gvim with patch 1677. Plugin vimcomplete is installed using K-takata minipac.
For completion I prefer to use Tab instead C-n.

If I add g:vimcomplete_tab_enable = 1 to my vimrc Gvim/vim throws following error:

Error detected while processing C:\Users\bozid\vimfiles\pack\minpac\start
\vimcomplete\plugin\plugins.vim[18]..function completor#Enable[17]..util
#TabEnable:
line    4:
E31: No such mapping
E31: No such mapping

Am I doing something wrong?

Best,
boput

**Comment by girishji** [comment]
I fixed the issue.  Upgrade to new version and try again.

https://github.com/girishji/vimcomplete/commit/2950eee33379585ee1f05ab0cfb9b8a538ce32f7
