### ISSUE TITLE
Error detected while processing BufRead Autocommands for "*"..function completor#Enable: E31: No such mapping

### ISSUE THREAD

**Issue by beavailable** [girishji/vimcomplete#20]
To Reproduce this error:
Run `vim` with any file or no file, press `i` to enter insert mode and type some letters, then exit insert mode and type `:h set`, you'll see the same error.

**Comment by girishji** [comment]
Cannot reproduce. Tried alwaysOn=true/false. Can you paste the full error message?

**Comment by beavailable** [comment]
Add this option you should be able to reproduce:
```vim
{'completor': {'noNewlineInCompletion': 1}}
```

**Comment by girishji** [comment]
Couldn't reproduce, but I see the bug anyway. Please try now. I think you had <cr> mapped to something earlier, which could provoke this bug.

**Comment by beavailable** [comment]
It's fixed and the error is gone, thanks for your work!

I use `lexima` and I think it maps `<cr>` to something to do its work.
