### ISSUE TITLE
What is the correct way to enable snippet support for the LSP?

### ISSUE THREAD

**Issue by riskygit** [girishji/vimcomplete#25]
Hi - just a quick question about vsnip support. There are a few relevant settings:

`VimCompleteOptionsSet`'s `vsnip/enable`,
`LspOptionsSet`'s `snippetSupport`
`LspOptionsSet`'s `vsnipSupport`

vimcomplete should _probably_ set the right options in the LSP, but for now, I'm not sure what the correct arrangement is. I think `snippetSupport` communicates the capability to the LSP, but I probably want vimcomplete's vsnip enabled and not the lsp plugin's? Additionally, I haven't yet seen a completion option marked as "snippet" yet... e.g. if I write `impl Ord for X` in Rust, it will suggest `cmp` and selecting it with `<C-Y>` will insert the unimplemented function. It's marked as `method`, but is that a snippet?

**Comment by girishji** [comment]
vimcomplete sets the right options in LSP. 
```
            snippetSupport: true, # snippets from lsp server
            vsnipSupport: false,
```
LSP client's vsnip completion gets disabled, but LSP's may send the snippets directly to vimcomplete. I have not seen meaningful snippets fro clang/jdtls/pylsp, but LSP server does mark them as 'Snippet'. See all possible kinds: https://github.com/yegappan/lsp/blob/main/autoload/lsp/completion.vim (line 15).

**Comment by riskygit** [comment]
I must've missed that. Thanks.

**Comment by girishji** [comment]
I also found `:h iabbrev` quite useful. Just FYI. You can see my hodgepodge abbrevs in https://github.com/girishji/dotfiles/blob/main/vim/.vim/after/ftplugin/python.vim and https://github.com/girishji/dotfiles/blob/main/vim/.vim/after/ftplugin/vim.vim
