### ISSUE TITLE
Fuzzy completion support

### ISSUE THREAD

**Issue by beavailable** [girishji/vimcomplete#26]
This [lsp](https://github.com/yegappan/lsp) plugin support fuzzy completion, but it doesn't work, I thought maybe it's because `vimcomplete` doesn't support fuzzy completion?
And not only for `lsp` plugin, I want fuzzy completion for everything, so could you add fuzzy completion support? Thanks a lot.

**Comment by girishji** [comment]
- For LSP you have to set the `completionMatcher` option to `fuzzy` in the LSP client itself. Please try and let me know.
- I have added fuzzy option to buffer completion

For other completion sources, either it is of marginal value or it is not possible give the source of items.

**Comment by beavailable** [comment]
Good, thanks.
I've tried, but I got an error:
```
Error detected while compiling VimEnter Autocommands for "*"..function VimCompleteOptionsSet[17]..<SNR>21_RegisterPlugins[11]..<lambda>1[4]..buffer#Completor[38]..<SNR>23_BufWords:
line   35:
E1012: Type mismatch; expected list<dict<any>> but got list<string>
```

**Comment by beavailable** [comment]
And you should remove `icase` option description from `README.md`

**Comment by girishji** [comment]
What version of Vim is this? Looks like `matchfuzzy()` is returning a list of strings instead of dicts. I cannot reproduce it with v9.1.

<img width="829" alt="Screenshot 2024-02-22 at 9 17 45 AM" src="https://github.com/girishji/vimcomplete/assets/16529248/c8eaddec-ab22-493a-a868-750acc817536">

**Comment by girishji** [comment]
Do you have this? https://github.com/vim/vim/pull/12574/files

**Comment by beavailable** [comment]
I'm using v9.0 on debian 12.

> Do you have this? https://github.com/vim/vim/pull/12574/files

Seems not, because this pull request was merged on jun 24, 2023, but debian migrated vim 9.0.1378 to testing on May 12, 2023 (link: https://tracker.debian.org/pkg/vim).

**Comment by girishji** [comment]
fixed
