### ISSUE TITLE
Enhancement request: make the path completion to complete relative path and not absolute path

### ISSUE THREAD

**Issue by basilgood** [girishji/vimcomplete#3]
Thanks for your work.
I just start using it and I like it.
What it's not fit to my preferences is the path completion.
It's complete, like default vim path completion ```<C-X><C-F>``` and it's an absolute path.
I think it's not very useful this absolute path completion.

Example:
- one folder named ```test``` with one subfolder named ```subfolder```
- in subfolder are two files: file-one and file-two
- in file-one which is in subfolder, if I type ```./``` it shows ```./subdir/ [path]``` but I want to see ```file-one [file]``` and ```file-two [file]```

Maybe it's possible to have a choice what kind of path completion to use: absolute or relative to current buffer.
Mucomplete has this possibility: [mucomplete-buffer-relative-path](https://github.com/lifepillar/vim-mucomplete/blob/03bcd4a7dfe0a2f6d432e8ce936d35273a15209d/doc/mucomplete.txt#L461C22-L461C22)

**Comment by girishji** [comment]
Good idea! I added an option `bufferRelativePath` to path completion. It should work as you suggested.

**Comment by basilgood** [comment]
Works perfectly thank you.

**Comment by girishji** [comment]
welcome!
