### ISSUE TITLE
Can't select previous menu item with `<S-Tab>`

### ISSUE THREAD

**Issue by beavailable** [girishji/vimcomplete#33]
I've set this in `vimrc`, and `<Tab>` key works well:
```vim
let g:vimcomplete_tab_enable = 1
```

**Comment by beavailable** [comment]
> You can input vim cmd `:verbose map <s-tab>` watch if another plugin uses the `<s-tab>` key

No other plugins use `<S-Tab>`, this is the output of `:verbose map <s-tab>`:
```vim
Kitty keyboard protocol: Cleared
s  <S-Tab>     * VCCleverSTab()
        Last set from ~/.vim/plugged/vimcomplete/autoload/util.vim line 31
```

**Comment by girishji** [comment]
do `cat > /dev/null` and type <s-tab>. what does that output?

**Comment by beavailable** [comment]
> do `cat > /dev/null` and type shift-tab. what does that output?

^[[Z

**Comment by beavailable** [comment]
I just found something weird, if I add this (in `vimrc`):
```vim
au BufRead * inoremap <expr> <s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
```
It could work. however if I map `<s-tab`> on `BufEnter` it doesn't work.

**Comment by girishji** [comment]
Your keymap is setup correctly as the 'verbose' command indicates. But I see a '*'. It is good to keep keymaps local to buffer. So I comitted new change. Can you upgrade and see if anything improves?

**Comment by beavailable** [comment]
Yes, it works just fine.
Thanks for fixing this!
