### ISSUE TITLE
How to link to lsp

### ISSUE THREAD

**Issue by DanielViberg** [girishji/vimcomplete#4]
Can you detail how i link this to https://github.com/yegappan/lsp?
I'm not getting any lsp suggestions using:

 var options = {                                                                                     
      completor: { shuffleEqualPriority: true },                                                      
     buffer: { enable: true, priority: 10 },                                                         
     lsp: { enable: true, priority: 8 },                                                             
 }                                                                                                   
 autocmd VimEnter * g:VimCompleteOptionsSet(options)

**Comment by girishji** [comment]
- Can you paste the output of command `:VimCompleteCompletors`?
- Have you configured the LSP server through `LspAddServer()`? See https://github.com/yegappan/lsp
- Install https://github.com/girishji/lsp-complete.vim if not already installed

**Comment by DanielViberg** [comment]
`{'name': 'path', 'priority': 11, 'completor': function('path#Completor')}
{'name': 'lsp', 'priority': 10, 'completor': function('lspcomplete#Completor')}
{'name': 'vsnip', 'priority': 9, 'completor': function('snippet_complete#Completor')}
{'name': 'buffer', 'priority': 8, 'completor': function('buffer#Completor')}`

Without this plugin i get completions for php and vue files. With this plugin i only get suggestions for php file, but no vim-snips.

**Comment by DanielViberg** [comment]
Installing by the provided instructions:
`
x vimcomplete.vim:                                                                                                                                     
     Cloning into '/home/daniel/.vim/plugged/vimcomplete.vim'...
     remote: Repository not found.
     fatal: repository 'https://github.com/girishji/vimcomplete.vim.git/' not found
`
Might be a reason for why I'm on outdated version?

**Comment by girishji** [comment]
You are using wrong url. Try `https://github.com/girishji/vimcomplete.git`

**Comment by DanielViberg** [comment]
Ok, that link works. But the symptoms are the same, this is my completorslist after updating the plugin:
`{'name': 'path', 'priority': 11, 'completor': function('path#Completor')}\n{'name': 'buffer', 'priority': 10, 'completor': function('buffer#Completor')}\n
{'name': 'lsp', 'priority': 8, 'completor': function('lspcomplete#Completor')}
`

**Comment by girishji** [comment]
Can you post your LSP server settings?

**Comment by girishji** [comment]
This plugin works with vim9 LSP client only. Please configure your volar server by following instructions here:

https://github.com/yegappan/lsp/wiki#volar-server
