### ISSUE TITLE
Completion source appears twice occasionally (e.g. when backspacing or when a single character is present)

### ISSUE THREAD

**Issue by riskygit** [girishji/vimcomplete#42]
Hi there. Sometimes, the source appears twice (e.g. `[lsp] [lsp]`)... here are a couple videos showing it happening (in a Rust file and a TypeScript file). Interestingly, it shows when backspacing in Rust but only when a single character is present in TypeScript. If you can't reproduce, I'll try to isolate potential config issues.

I should add I'm using your PR to Vim that fixes `<c-p>`.

Edit: out of curiosity, why do buffer-sourced completions have a type (e.g. `k`)? The buffer wouldn't be aware of that.

https://github.com/girishji/vimcomplete/assets/105889909/2a35ee92-3537-428b-9db7-a8fa2b23c29b

https://github.com/girishji/vimcomplete/assets/105889909/211c51bb-64cc-4766-a27c-6e87c606ff30

**Comment by girishji** [comment]
Maybe try this https://github.com/girishji/vimcomplete/commit/e9620b6456f8d13287cabf5c2be2b52a45f16042

**Comment by riskygit** [comment]
Not quite!

![image](https://github.com/girishji/vimcomplete/assets/105889909/e05dba78-209a-4e17-a5bc-3ce29537c822)

**Comment by girishji** [comment]
I think the lsp server is sending really weird info.
Try https://github.com/girishji/vimcomplete/commit/cf7949c1dd17631ed29ac7a8f8c867ab7f415e1a

**Comment by girishji** [comment]
I have another idea. Maybe put the [lsp] in the 'kind' field, in addition to the letter.

**Comment by riskygit** [comment]
Still seeing it (only if there is extra info, though). Your idea sounds good.

![image](https://github.com/girishji/vimcomplete/assets/105889909/91e7d0d6-2319-47e8-89d5-a7a5014a082a)

**Comment by girishji** [comment]
That means LSP is sending what should have been in 'info' into 'menu' field.

**Comment by girishji** [comment]
How can I reproduce this?

**Comment by riskygit** [comment]
You can create the same TypeScript environment you used to test the other bug; the second video shows it happening in TS when there is a single character present.

**Comment by girishji** [comment]
Not happening to me

<img width="574" alt="Screenshot 2024-03-19 at 9 25 54 PM" src="https://github.com/girishji/vimcomplete/assets/16529248/61558707-fef6-47e1-8828-d1bcd48af18e">

**Comment by girishji** [comment]
Try this new version.

**Comment by riskygit** [comment]
That seems to have fixed it!
