### ISSUE TITLE
[buffer completion]  candidates for CJK characters are truncated

### ISSUE THREAD

**Issue by lxhillwind** [girishji/vimcomplete#47]
When inputting CJK characters, candidates are generated unconditionally, and item in the candidates is truncated.

![image](https://github.com/girishji/vimcomplete/assets/10025859/d93b476e-f9a3-4011-90cb-69849d49fae9)

In this picture, I have input `睡大觉`, buffer completion suggests `睡大<e8>`; `<e8>` is actually the first byte of `觉`:

```console
% printf 觉 | xxd
00000000: e8a7 89                                  ...
```

I have "fixed" it (I will create PR later), but the fix replaces a call to `strpart()` with `matchstr()`: I don't know if it will cause performance issue when input is large.

**Comment by girishji** [comment]
Can you try `strcharpart()` or `slice()`?
