### ISSUE TITLE
omnifunc complete does not work with syntaxcomplete#Complete

### ISSUE THREAD

**Issue by phongnh** [girishji/vimcomplete#49]
Hi,

I just found that there is an issue when using `omnifunc` complete with `syntaxcomplete#Complete`. When opening Gemfile in Rails project, somehow this file's `omnifunc` is set to `syntaxcomplete#Complete`.

When typing `gem "`, everytime I type `"` I got this error:

<img width="1512" alt="image" src="https://github.com/girishji/vimcomplete/assets/438791/9751535c-092c-46d9-badd-daa8ed5116f5">

Tried to check the source code, it looks the it is failed at `autoload/vimcomplete/omnifunc.vim:44`, but I don't know how to fix that.

Could you please help to fix this issue? Thanks.

**Comment by girishji** [comment]
Let me look into it.

**Comment by girishji** [comment]
My Vim automatically sets omnifunc in Gemfile to `rubycomplete#Complete`. Maybe try this.

**Comment by phongnh** [comment]
> My Vim automatically sets omnifunc for Gemfile to `rubycomplete#Complete`. Maybe try unsetting it in your .vimrc and let Vim set it.
> 
> Also, I cannot reproduce the problem with `syntaxcomplete#Complete`
> 
> Disable Lsp.

Tried to set its omnifunc to `rubycomplete#Complete`, it works fine. I did not use Lsp by the way. Thanks.

It seems that `syntaxcomplete#Complete` also does not work with other completion plugins. Previously, I tried to set this in my vimrc

```vim
" after/ftplugin/ruby.vim
if exists('&omnifunc') && &omnifunc ==# 'syntaxcomplete#Complete'
    setlocal omnifunc=
endif
``` 

Thanks for your support.
