### ISSUE TITLE
Fuzzy support

### ISSUE THREAD

**Issue by Sharpeee** [girishji/vimcomplete#5]
Hi. First, thanks for a great plugin!

Would it be possible to have fuzzy completion?

**Comment by girishji** [comment]
Possible. Do you have something specific in mind, like fuzzy completion for buffer words but not for LSP words?

**Comment by Sharpeee** [comment]
I was just thinking for everything, but now that you mention it, maybe it would be a good idea to be able to turn it on and off for the individual completers.

Personally, I am mostly missing it for LSP.

**Comment by girishji** [comment]
Have you tried setting `completionMatcher: 'fuzzy'` in your LSP configuration? LSP fuzzy complete should work as is.

**Comment by Sharpeee** [comment]
I did not know I could do that. Just tried it, and it does not do a good job at fuzzy completion.

For example, if I type (in Python) `bp` I would expect `breakpoint` to be in the list, but it is not. Additionally, if a variable has a name like `foo_bar`, I would expect `fb` to work, but again, it does not.

**Comment by girishji** [comment]
It completes `breakpoint` for me, from `bp`. `foo_bar` also works for me. Have you changed `maxCount` value? I am using pyright:

```
    {
        name: 'pyright',
        filetype: 'python',
        path: exepath('pyright-langserver'),
        args: ['--stdio'],
        # debug: true,
        workspaceConfig: {
            python: {
                analysis: {
                    autoSearchPaths: true,
                    diagnosticMode: 'workspace',
                    autoImportCompletions: true,
                    typeCheckingMode: "off", # off, basic, strict
                },
            },
        },
    },
```

**Comment by Sharpeee** [comment]
I am using jedi_language_server. I mistakenly thought the fuzzy support was supposed to be handled from your side, but that is of course not the case (which makes sense when I think about it).
