### ISSUE TITLE
Expand lsp snippets/functions

### ISSUE THREAD

**Issue by expoodo** [girishji/vimcomplete#50]
Is there a way to expand LSP functions/snippets? I have installed the necessary vsnip plugins and the Vim9 LSP plugin. Vsnip is enabled in the options and shown in `:VimCompleteCompletors` but when I press enter on a function, vimcomplete only inserts the function name.

**Comment by girishji** [comment]
After selecting the snippet type `<space>`, and see if it works. If Lsp snippets are not expanding, can you share your more details? Which Lsp server and which snippet?

**Comment by girishji** [comment]
`<space>` should expand the snippet, after you tab select. This works for vsnip snippets. It should work for Lsp snippets also. If not, let me know which Lsp server and which snippet.

**Comment by expoodo** [comment]
Tried that, but didn't work. I'm using clangd as the language server. Here's what I tried doing:


https://github.com/girishji/vimcomplete/assets/60551350/3c0875e1-95d5-467c-9d12-501779be02b0



> <cr> will not expand snippet

I mapped <cr> to <c-y> using `inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"` if that helps.

**Comment by girishji** [comment]
Have you unset `completionTextEdit` by any chance? In any case, it should have been set explictly in this plugin.
Can you try now?

**Comment by expoodo** [comment]
Doesn't seem to work for me, I have checked that `completionTextEdit` is enabled. `<c-y>` doesn't insert the snippet, and `<space>` doesn't seem to do anything


https://github.com/girishji/vimcomplete/assets/60551350/cd2eeb31-cc64-4b5a-a03f-ce73cbe7c6fd

**Comment by girishji** [comment]
- Can you check `:imap` and make sure you have no mapping for space and c-y?
- Disable this plugin (or remove it), and try only Lsp client and check if it completes.
- Set debug to true,  `g:VimCompleteOptionsSet({completor: { debug: true}})`, and type `#inc` and let the popup window appear, then do `:messages` and paste the output.

**Comment by expoodo** [comment]
Actually found out that it was something else causing it. I used an autocmd to `packadd lsp` on certain filetypes, and I suppose that messed with the snippet support. I reverted the commit that referenced this issue, and it didn't change anything.

Thank you
