### ISSUE TITLE
LSP snipets description view problem

### ISSUE THREAD

**Issue by greeschenko** [girishji/vimcomplete#51]
Hello, I use yegappan/lsp with ultisnipsSupport  = true and  there how it look with this plugin

![20240331-222823_1920x1080](https://github.com/girishji/vimcomplete/assets/2754533/157d06c2-5693-472b-8a04-dc1c46c46bc2)

and with lsp completion 

![20240331-222914_1920x1080](https://github.com/girishji/vimcomplete/assets/2754533/579f91b7-7bdf-4ff3-b3d3-5c34de88b136)

Please tell me how I can fix this.

thank you

**Comment by girishji** [comment]
This plugin does not support ultisnips. I suppose it could support ultisnips, but is there a reason why you are not using vsnip?

**Comment by greeschenko** [comment]
Hello I use ultisnip for the very long time and have many custom snippets for it in my config, I dont use vsnip because it not run with  yegappan/lsp for me, I tryed to use it with this plugin but no luck vsnip dont work 

![20240402-143520_1920x1080](https://github.com/girishji/vimcomplete/assets/2754533/66331fa6-bab7-4a9f-82e6-786249b16838)

I will try resolve this problem and send pull request if I will find solution

**Comment by girishji** [comment]
Set   `customInfoWindow = false` to keep default look of window. I think you are using a font without box characters.
