### ISSUE TITLE
completion only after certain numbers of characters typed

### ISSUE THREAD

**Issue by dacyberduck** [girishji/vimcomplete#52]
It would be helpful if there is an option that limits the popup menu to open only after certain numbers of characters are typed. For example completion menu will only popup when at least 3 characters are present at cursor. However it shouldn't affect lsp's "." or "->" completions.

**Comment by girishji** [comment]
It is possible to add this option. When LSP returns completion candidates there is no way to know (without some effort) whether it is completing because of trigger chars (".", ">") or not. Is there so much value in this feature?

**Comment by girishji** [comment]
Done. Set `triggerWordLen` to 3.

**Comment by dacyberduck** [comment]
Thanks.
