### ISSUE TITLE
Vimcomplete Options Not Respected in Vimscript?

### ISSUE THREAD

**Issue by chris414862** [girishji/vimcomplete#53]
I would like to use vimcomplete, but my `.vimrc` has been built over the years in vimscript, not vim9script. I have tried converting the sample options given in the documentation to vimscript syntax (sorry, employer seems to have disabled screenshot uploads here):
```
let vcoptions = {
\   "buffer": {"enable": 1, "priority": 10},
\   "lsp": { "enable": 0},
\   "omnifunc": { "enable": 1, "priority": 11 }
\}
autocmd VimEnter * g:VimCompleteOptionsSet(vcoptions)
```

When I open a file with vim I can tell that vimcomplete is operational, but it appears to only be getting completions from the buffer completer. If I manually use `<C-X><C-O>` to activate omnicompletion, I am presented with a different set of completions (ones that are object-member aware for python builtin packages). This is even true when I disable buffer completions.

I suspect that the configuration options in my `.vimrc` are not being respected, possibly because there is some fatal error occurring in the translation of vimscript to vim9script. Am I on to something? Is there anyway I can use vimcomplete without re-writing my (perhaps way to long) `.vimrc` in vim9script?

This is my vim version if it helps:
```
$ vim --version  
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 05 2024 19:39:07)
...
```

**Comment by girishji** [comment]
It's unlikely a vim9 vs vim issue. Can you do `:echo &omnifunc` and check? Also do `:VimCompleteCompletors` and check that omnicompletion is active. What type of file is this? Is this your own custom omnifunc?

**Comment by chris414862** [comment]
Should enable be set to false? Perhaps I am confused about what enable means in this context...

In any event, assuming that was a typo, the output of `echo &omnifunc` is:
```
python3complete#Complete
```
and the output of `:VimCompleteCompletors` is:
```
{'name': 'path', 'priority': 13, 'completor': function('vimcomplete#path#Completor')}
{'name': 'buffer', 'priority': 12, 'completor': function('vimcomplete#buffer#Completor')}
```
I find this especially odd. I defined the priority of buffer completion to be 10 in the configuration settings...

I feel that this is more evidence that my `.vimrc` settings above are not being read properly somehow. This behavior is still present with a minimal `.vimrc` that just contains the plugin install and the configurations supplied above

**Comment by chris414862** [comment]
Just for completeness, I want to relay the output of an additional setting. Even though my buffer had a python file in it, I explicitly gave the omnifunc completer the filetypes as you suggested:
```
let vcoptions = {
\   "buffer": {"enable": 1, "priority": 10},
\   "lsp": { "enable": 0},
\   "omnifunc": { "enable": 1, "priority": 11, "filetypes": ['python', 'javascript']}
\}
autocmd VimEnter * g:VimCompleteOptionsSet(vcoptions)
```
and the output of the `echo &omnifunc` and `:VimCompleteCompletors` commands was the same as I wrote above. I even set `"enable":0` (in legacy vimscript) to match your `enable: false` suggestion (in vim9script) with no change in behavior.

Not sure how to resolve this at this point

**Comment by girishji** [comment]
My apologies, `"enable"` needs to be set to true (`1` or `v:true`). Also, I simplified the configuration. You do not need to specify filetype, unless you want to restrict omnifunc to specific file types.
```
"omnifunc": { "enable": 1}
```

**Comment by chris414862** [comment]
I have installed your updates, however the problem persists. I have found a minimal example you can perhaps test yourself. Using this legacy vimscript .vimrc you should be able to reproduce the issue:
```
call plug#begin()
Plug 'girishji/vimcomplete'
call plug#end()

let vcoptions = {
\   "buffer": {"enable": 0, "priority": 10},
\   "lsp": { "enable": 0},
\   "omnifunc": { "enable": 1, "priority": 11, "filetypes": ['python', 'javascript']}
\}
autocmd VimEnter * g:VimCompleteOptionsSet(vcoptions)
```
With this `.vimrc` when I start a new vim process with a file, the `VimCompleteCompleters` command produces this output:
```
{'name': 'path', 'priority': 13, 'completor': function('vimcomplete#path#Completor')}
{'name': 'buffer', 'priority': 12, 'completor': function('vimcomplete#buffer#Completor')}
```
Not only was the omnifunc not enabled, but but the buffer completer was *not* disabled. 

Listing all the autocommand functions for the VimEnter event with `:autocmd VimEnter` we get this:
```
--- Autocommands ---
VimEnter
    *         g:VimCompleteOptionsSet(vcoptions)
              lsp.Setup()
    *         doau <nomodeline> User VimCompleteLoaded
FileExplorer  VimEnter
    *         sil call s:VimEnter(expand("<amatch>"))
```
So at least the command itself was registered.
  
However, if I use this equivalent vim9script `.vimrc`(at least I think it's equivalent):
```
vim9script
plug#begin()
Plug 'girishji/vimcomplete'
plug#end()

var vcoptions = {
   buffer: {enable: false, priority: 10},
   lsp: { enable: false},
   omnifunc: { enable: true, priority: 11}
}
autocmd VimEnter * g:VimCompleteOptionsSet(vcoptions)
```
Then things work as expected. In a new vim process  `VimCompleteCompleters` command produces this output:
```
{'name': 'path', 'priority': 13, 'completor': function('vimcomplete#path#Completor')}
{'name': 'omnifunc', 'priority': 11, 'completor': function('vimcomplete#omnifunc#Completor')}
```
Which is more in line with what I would expect. The buffer completer was disabled correctly and the omnifunc completer was included. 

I'm not so familiar with the behaviors of either scripting language to be honest, but to me this looks like something is going on when using one versus the other.

**Comment by girishji** [comment]
This is strange. It works for me as follows. my `~/.vimrc`:
```
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin()
Plug 'girishji/vimcomplete'
call plug#end()

let vcoptions = {
\   "buffer": {"enable": 0, "priority": 10},
\   "lsp": { "enable": 0},
\   "omnifunc": { "enable": 1, "priority": 11, "filetypes": ['python', 'javascript']}
\}
autocmd VimEnter * call g:VimCompleteOptionsSet(vcoptions)
```

Then I did `:PlugUpdate`. 

Then open `test.py`, and I get 
```
{'name': 'path', 'priority': 13, 'completor': function('vimcomplete#path#Completor')}
{'name': 'omnifunc', 'priority': 11, 'completor': function('vimcomplete#omnifunc#Completor')}
Press ENTER or type command to continue
```

**Comment by chris414862** [comment]
Yes I just found that as well. See! There *was* an issue with translating from vim9script to vimscript. It was that I don't know how to do it properly! Doh! 

Sorry about that. I don't often venture into writing autocommands so I wasn't aware of the syntax. I did look at the vim help docs for this but it said:
```
:au[tocmd] [group] {event} {aupat} [++once] [++nested] {cmd}
```
I didn't realize `call` was part the syntax for `cmd` in legacy vimscript and not vim9script.

Perhaps one example in your readme with the legacy syntax might prevent this issue for others?  I think there is a chance others will have an issue with this. I feel that syntactical difference is probably not well known to the casual vim user and, unfortunately, no obvious errors were thrown to let me know there was an issue.

**Comment by girishji** [comment]
> Perhaps one example in your readme with the legacy syntax might prevent this issue for others? 

I realized this and added a prominent note already.

> I didn't realize call was part the syntax for cmd in legacy vimscript and not vim9script.

`{cmd}` usually refers to Ex commands that you execute in command-line. In this context it also includes function calls and other 'expressions'. Because of this 'polymorphism' it just fails to throw an error when it should. There are many other quirks with legacy script. Vim9script is more predictable. This is why I would not touch legacy script if I don't have to.
