### ISSUE TITLE
Is FZF style completion listing possible?

### ISSUE THREAD

**Issue by hammymath** [girishji/vimcomplete#55]
1. apples
2. app
3. apply

typing "apl" currently does not give apples as a potential result completion. I think it would be a beneficial feature.

**Comment by girishji** [comment]
Can you try setting option `completionMatcher` to `fuzzy` for buffer completion?

```
    g:VimCompleteOptionsSet({
        buffer: { enable: true, completionMatcher: 'fuzzy' }


```
