### ISSUE TITLE
tmux completion source

### ISSUE THREAD

**Issue by pbnj-dragon** [girishji/vimcomplete#56]
Would it be possible to add support/integration for [tmux completion](https://github.com/wellle/tmux-complete.vim) source?

**Comment by girishji** [comment]
Certainly possible. In the meantime, can you set `g:tmuxcomplete#trigger = 'omnifunc'`, and enable omnifunc: `g:VimCompleteOptionsSet({ omnifunc: { enable: true } })` and see how far you get.

**Comment by pbnj-dragon** [comment]
If I understand the docs correctly, enabling `omnifunc` would conflict with LSP completion and require me to disable LSP.

![image](https://github.com/girishji/vimcomplete/assets/135638833/f4934533-500d-40df-98b9-0d4ee52fce64)

**Comment by girishji** [comment]
Yes, forgot about that. I do not use tmux. Can you please disable LSP and try again? I think tmux-completion works in async and sync modes. I'd be curious to know how well their omnifunc works, when you have couple of tmux windows open.
