### ISSUE TITLE
svelte autocmpletion doesn't work with tailwindcss autocompletion

### ISSUE THREAD

**Issue by maximyurevich** [girishji/vimcomplete#57]

**Comment by girishji** [comment]
What does this mean?

**Comment by maximyurevich** [comment]
> What does this mean?

Tailwindcss ls autocompletion doesn't work with svelte ls enabled, also html ls autocompletion doesnt work with emmet ls in the same time

**Comment by girishji** [comment]
Sorry I am not a web developer. I still have no idea. Maybe you can provide me a configuration where I can reproduce this problem.
