### ISSUE TITLE
Question about LSP keywordOnly option

### ISSUE THREAD

**Issue by heavenshell** [girishji/vimcomplete#58]
Hi, first of all, thank you for creating awesome plugin!

I have some question about LSP's keywordOnly option. 

https://github.com/girishji/vimcomplete/blob/01bae49930c1081ecb583b855f8b12110a83bb0e/doc/vimcomplete.txt#L327-L330

According to the document, when keywordOnly option is `false`, LSP candidates popup after `.` typed.
But It seemed to show LSP candidates regardless of keywordOnly option.

<img width="650" alt="スクリーンショット 2024-05-12 10 41 47" src="https://github.com/girishji/vimcomplete/assets/56591/1fbd8aa5-7553-4a35-af3d-003deda2efc6">

When I type `f` and candidates popup and candidates are include LSP's candidates.
I thought it didn't show LSP candidates until I hit the dot, but it does.

When the keywordOnly option is set to true, it works as documented.
I would like to know the difference between the keywordOnly option.
(Also I would like the LSP candidates to be displayed when I enter the dot)

Here is my settings.
```vim
const options = {
  lsp: {
      enable: true,
      keywordOnly: false,
    }
}
g:VimCompleteOptionsSet(options)
```

Thank you!

**Comment by Shougo** [comment]
I think the option works also keyword.

So `keywordOnly` option is false: keyword completion like `f` and dot completion.

**Comment by heavenshell** [comment]
@girishji Thank you for answer.
>When true it prevents LSP from completing unless the prefix is a keyword -- so, it prevents completion after . or (, etc.

Now I understood. I thought this option is only enter `.`(or lsp's completionProvider's triggerCharacters) can popup candidates.

>I don't remember the use case why this option was added. Maybe it should be removed to keep things simple.

Yeah, I think this is bit a confusing.
