### ISSUE TITLE
Cannot use omnifunc for some filetypes when LSP is enabled (for any other filetype)

### ISSUE THREAD

**Issue by khardix** [girishji/vimcomplete#65]
I'm trying to use omnifunc for filetypes where a LSP is not available or not suitable for me. Minimal example:

```vim
vim9script

final complete_options = {
    omnifunc: {
        enable: true,
        filetypes: ['tex'],
    },
    lsp: {
        enable: true,
        filetypes: ['python'],
    },
}
autocmd VimEnter * g:VimCompleteOptionsSet(complete_options)
```

When editing `*.tex` file, the omnifunc completor is reported as enabled:

```
{'name': 'omnifunc', 'priority': 8, 'completor': function('vimcomplete#omnifunc#Completor')}
```

However, no entries are being completed unless I directly invoke `<C-x><C-o>`.  On the other hand, when I set `lsp: {enable: false, …}` in the options, the omnifunc completions springs to life automatically as I would expect.  No LSP for Python then, though. 🙁

I suspect the following line is the culprit:
https://github.com/girishji/vimcomplete/blob/4c80d44b8776c125a55cd506b6e5a4478c3d0d7d/autoload/vimcomplete/omnifunc.vim#L14

This should probably check if LSP is enabled for the current buffer, not globally (if I'm reading that correctly).

**Comment by girishji** [comment]
Fixed the bug. Please try again.

**Comment by khardix** [comment]
Now it works! Thanks!
