### ISSUE TITLE
Omni completion not work in GVIM in windows10

### ISSUE THREAD

**Issue by leoingru** [girishji/vimcomplete#66]
Tested with python programing, the completion menu could be invoke **Only** by keypress  `ctrl-x ctrl-o`,  but not automatically invoked when in windows10.  This bug  not happend under linux

**Comment by girishji** [comment]
`ctrl-x ctrl-o` triggers omni-completion. I do not use windows10. What is the output of `:VimCompleteCompletors` command?

**Comment by leoingru** [comment]
only `buffer` and  `path` sources
![image](https://github.com/girishji/vimcomplete/assets/171112518/e0f4e41b-3dff-4b20-b2c7-f636a7ec67f4)



> `ctrl-x ctrl-o` triggers omni-completion. I do not use windows10. What is the output of `:VimCompleteCompletors` command?

**Comment by girishji** [comment]
You have to enable either `lsp` or `omnifunc`. See the README.

**Comment by leoingru** [comment]
actually   lsp is `disabled`,  omni is `enabled`,   my config works under `linux`  but not `win10`

```
vim9script
g:vimcomplete_tab_enable = 0
var options = {
    showSource: true,
    alwaysOn: false,
    completor: { shuffleEqualPriority: true, postfixHighlight: true },
    buffer: { enable: true, priority: 10, urlComplete: true, envComplete: true },
    abbrev: { enable: true, priority: 10 },
    omnifunc: { enable: true, priority: 8},
    vsnip: { enable: true, priority: 16 },
    vimscript: { enable: true, priority: 12 },
    lsp: { enable: false, priority: 10, maxCount: 5 },
    ngram: { enable: false, priority: 10 },
}
autocmd VimEnter * g:VimCompleteOptionsSet(options)

```

**Comment by leoingru** [comment]
above config gave me  below sources when `Linux`
![image](https://github.com/girishji/vimcomplete/assets/171112518/d04198bb-664d-41ea-83ac-d8b67957e8d7)

**Comment by girishji** [comment]
what do you see when you do `:echo &omnifunc` or `:set omnifunc?` in windows?

**Comment by leoingru** [comment]
`:echo &omnifunc` gave me  empty string, and   `:set omnifunc?`  resulted in ` omnifunc= `
> what do you see when you do `:echo &omnifunc` or `:set omnifunc?` in windows?

**Comment by girishji** [comment]
So, there is the problem. You should see `python3complete#Complete` (compare in Linux). You Vim installation may have issues on Windows.

**Comment by leoingru** [comment]
sorry,   I forgot  open python file before  checking  omni setting,  accutualy it gave me `python3complete#Complete` when a python file opend in `Win10`

**Comment by girishji** [comment]
Can you upgrade and try now?

**Comment by leoingru** [comment]
> Can you upgrade and try now?

not work , this is what I got aftter opening a `test.py` file
![image](https://github.com/girishji/vimcomplete/assets/171112518/3459582c-32b1-4550-baf7-c8ef6012fc85)

**Comment by girishji** [comment]
Mmm, why no `omnifunc`, `vsnip`, `abbrev`? You have not configured VimComplete through `g:VimCompleteOptionsSet()`. Check your `.vimrc` on windows10

**Comment by arozehnal** [comment]
Hmm, I have exactly the same problem as leoingru.
I also have Win10, legacy .vimrc, vim-plug manager, 
omni setting gave me python3complete#Complete.

The plugin is very promising, maybe just missing a few lines in the documentation? Exact listing of what to put where and how to check the settings made, some conditional logging (?).

I've now reduced the .vimrc to only read the vimcomplete plugin. I don't know what else I could check in vimrc?
