### ISSUE TITLE
E133：return not inside a function

### ISSUE THREAD

**Issue by sqlmap3** [girishji/vimcomplete#68]
vimcomplete/autoload/vimcompelte/lsp.vim line 79：

**Comment by girishji** [comment]
can you elaborate?

**Comment by sqlmap3** [comment]
vimcomplete/autoload/vimcompelte/lsp.vim line 79：
E133：return not inside a function

there is full error.

**Comment by sqlmap3** [comment]
Error detected while processing VimEnter Autocomands for "*",scrpts  vimcomplete/autoload/vimcompelte/lsp.vim line 79：E133：return not inside a function

**Comment by girishji** [comment]
What version of Vim? How do I reproduce this? Please provide more details. I do not see this error in my setup.

**Comment by sqlmap3** [comment]
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@x86-vm-26.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Aug 18 14:50:17 EDT 2020

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 27 2023 22:25:47)
Compiled by root@ciccmp513
Huge version with GTK2 GUI. Features included (+) or not (-):
+acl +file_in_path +mouse_urxvt -tag_any_white
+arabic +find_in_path +mouse_xterm -tcl
+autocmd +float +multi_byte +termguicolors
+autochdir +folding +multi_lang +terminal
-autoservername -footer -mzscheme +terminfo
+balloon_eval +fork() +netbeans_intg +termresponse
+balloon_eval_term +gettext +num64 +textobjects
+browse -hangul_input +packages +textprop
++builtin_terms +iconv +path_extra +timers
+byte_offset +insert_expand -perl +title
+channel +ipv6 +persistent_undo +toolbar
+cindent +job +popupwin +user_commands
+clientserver +jumplist +postscript +vartabs
+clipboard +keymap +printer +vertsplit
+cmdline_compl +lambda +profile +vim9script
+cmdline_hist +langmap -python +viminfo
+cmdline_info +libcall -python3 +virtualedit
+comments +linebreak +quickfix +visual
+conceal +lispindent +reltime +visualextra
+cryptv +listcmds +rightleft +vreplace
+cscope +localmap -ruby +wildignore
+cursorbind -lua +scrollbind +wildmenu
+cursorshape +menu +signs +windows
+dialog_con_gui +mksession +smartindent +writebackup
+diff +modify_fname -sodium +X11
+digraphs +mouse +sound -xfontset
+dnd +mouseshape +spell +xim
-ebcdic +mouse_dec +startuptime +xpm
+emacs_tags -mouse_gpm +statusline +xsmp_interact
+eval -mouse_jsbterm -sun_workshop +xterm_clipboard
+ex_extra +mouse_netterm +syntax -xterm_save
+extra_search +mouse_sgr +tag_binary
-farsi -mouse_sysmouse -tag_old_static
system vimrc file: "
VIM: "/tools/vim/9.0/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/uuid -I/usr/include/pixman-1 -I/usr/include/libdrm -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99 -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE -lm -ltinfo -lelf -lselinux -lcanberra -lrt -lacl -lattr -ldl

**Comment by girishji** [comment]
Can you upgrade Vim to 9.1 (latest) and try it? Many bugs were fixed regarding vim9 script artifacts.

**Comment by sqlmap3** [comment]
Unfortunately, my gvim is an offline workstation and I can't network to update it!

**Comment by girishji** [comment]
Try again pl.

**Comment by sqlmap3** [comment]
Unfortunately, configuration does not take effect

**Comment by sqlmap3** [comment]
`
export def GetTriggerKind(): number
    if !get(g:, 'loaded_lsp', false) || v:version < 901
        return -1
    endif
    
    import autoload 'lsp/buffer.vim' as buf
    var lspserver: dict<any> = buf.CurbufGetServerChecked('completion')
    var triggerKind: number = 1
    var line: string = getline('.')
    var cur_col = charcol('.')
    
    if line[cur_col - 2] !~# '\k'
        var trigChars = lspserver.completionTriggerChars
        var trigidx = trigChars->index(line[cur_col - 2])
        if trigidx == -1
            triggerKind = -1
        else
            triggerKind = 2
        endif
    endif
    
    return triggerKind
enddef
`
I modified it，but  there is a new error   named  as   <  error detected while compilingVim EnterAutocommands for "*"..Autocommands for "VimCompteteloaded"..function<SNR>56_RegisterPlugins[11]..<Lambda>1[4]..vimcomplete#completor#register[1]..<lambda>23: line 4: E117 unknow function :indexof >.  Maybe can use it  in  9.0.0196   .     [You have some plugin that needs a rather recent version of Vim (indexof() was added in 9.0.0196)](https://www.reddit.com/r/vim/comments/17ti3qt/missing_function_indexof_when_moving_cursor/)

**Comment by girishji** [comment]
You can implement `indexof()` yourself:

```
def IndexOf(lst: list<any>, str: string): number
    for [i, v] in lst->items()
        if v.name == str
            return i
        endif
    endfor
    return -1
enddef
```

Now replace `completors->indexof((_, v) => v.name == source)` with `IndexOf(completors, source)`.
I have not tested it, but it should work.

**Comment by girishji** [comment]
https://github.com/girishji/vimcomplete/commit/ba8e576c8348a848b0f90dd2fe865fa8f7a0564a
