### ISSUE TITLE
Double `#include` insertion with `clangd`

### ISSUE THREAD

**Issue by briancarbone** [girishji/vimcomplete#72]
Hi, there. When using `clangd` as my language server with https://github.com/yegappan/lsp, strange behavior is observed:

① If I select a completion entry and press `<Esc>`, the corresponding `#include` for that entry is inserted (which is surprising).
② If I select a completion entry and press, `<c-y>`, the corresponding `#include` for that entry is inserted twice. (Additionally, the function signature is entered, but that may just be a `clangd` "feature.")

Here's a brief video:
https://github.com/user-attachments/assets/4b948808-c992-467b-b5a1-07c843a01334

**Comment by girishji** [comment]
Looks like a bug. I will investigate tomorrow.

**Comment by girishji** [comment]
https://github.com/yegappan/lsp/issues/545

**Comment by girishji** [comment]
This looks like LSP client issue (https://github.com/yegappan/lsp/issues/545). In the meantime, you can set ` completionTextEdit` to `false` in LSP client configuration.

**Comment by girishji** [comment]
This is a LSP issue. The undesirable side-effect is for typescript server (and others maybe) that make text edits available at a later time. I have opened an issue in LSP, and it needs to be tracked there. This plugin should not set or unset `completionTextEdit` at all.
