### ISSUE TITLE
Support mapping custom completion kinds to colors

### ISSUE THREAD

**Issue by briancarbone** [girishji/vimcomplete#73]
This vim patch (https://github.com/vim/vim/commit/38f99a1f0d61e9bde3f4a3d0cbe2d06185c4a57f) seems to add the ability to have variance in the color of what vimcomplete uses for completion kind.

**Comment by girishji** [comment]
Pl. test it now. Define, for example, `PmenuKindKeyword` highlight group and check if colors change for 'Keyword' kind.

**Comment by briancarbone** [comment]
Seeing errors like `vimcomplete: 22 not found in dict` (the number changes).

**Comment by girishji** [comment]
Pl. try now.

**Comment by briancarbone** [comment]
With:

```
  hi PmenuKindFunction guifg=#4385be gui=italic
  hi PmenuKindKeyword guifg=#d14d41 gui=NONE
```

I see this:

![image](https://github.com/user-attachments/assets/d6a3fbd4-1e89-4941-86fc-28f76fa282b1)

Should the `f` be styled differently? Not sure if I did that incorrectly.

**Comment by briancarbone** [comment]
Oh, it's applying to `buffer` and not `lsp`.

**Comment by girishji** [comment]
Looks like a bug. Wait a min.

**Comment by girishji** [comment]
Pl. try now.

**Comment by briancarbone** [comment]
Looks great to me!

![image](https://github.com/user-attachments/assets/1c8fe5d1-9a12-490a-aa48-b2ee50df8329)

**Comment by girishji** [comment]
Maybe it is good to call [buffer] returned words a something other than 'keyword', and leave LSP 'kind's as unique..

**Comment by briancarbone** [comment]
I agree; that does make sense.

**Comment by briancarbone** [comment]
Potentially, you could set default "kind" highlights for the ones with obvious links like `PmenuKindKeyword -> Keyword`, `PmenuKindConstant -> Constant`, etc.

Up to you.
