### ISSUE TITLE
vim gives me an error every time when I starts it

### ISSUE THREAD

**Issue by pingzh1215** [girishji/vimcomplete#75]
There are some errors:

Error detected while processing VimEnter Autocommands for "*"..script /Users/hurray/.vim/plugged/vimcomplete/autoload/vimcomplete/
lsp.vim:
line   90:
E1044: Export with invalid argument:     export def GetTriggerKind(): number

I use macos and my vim version is 9.0.1424.

I am not sure how to resolve this problem.

**Comment by girishji** [comment]
Try now.

**Comment by pingzh1215** [comment]
Thanks, when I pulled the newest codes, all things were normal.
