### ISSUE TITLE
vimcomplete and Win10 

### ISSUE THREAD

**Issue by arozehnal** [girishji/vimcomplete#78]
OS: Windows 10  Pro build 19045.4894
Vim  9.1 64-bits - Portable installation 
env var VIM=d:\U\Vim9\vim91
vimrc= $VIM\\_vimrc
HOME=f:\Users\ro
custom Vim dir: $HOME\vimfiles
vim-plugin manager: vim-plug
directory with installed plugins: $HOME\vimfiles\plugged

```
# f:\Users\ro\vimfiles\after\plugin\opts_ro.vim 
vim9script
var dictproperties = {
    python: { sortedDict: false },
    text: { sortedDict: false }
}
var vimcomploptions = {
   completor: { shuffleEqualPriority: true, postfixHighlight: true },
   vimscript: { enable: true, priority: 10 },
   abbrev: { enable: true, priority: 10 },
   dictionary: { enable: true, priority: 11, filetypes: ['python', 'text'], properties: dictproperties },
   omnifunc: { enable: true, priority: 10, filetypes: ['tex', 'python'] },
   vsnip: { enable: true, priority: 10 }   
   }

g:VimCompleteOptionsSet(vimcomploptions)
```
After installing vimcomplete the same problems as #61 or #66...
:VimCompleteCompleters  show only:
```
{'name': 'path', 'priority': 13, 'completor': function('vimcomplete#path#Completor')}
{'name': 'buffer', 'priority': 12, 'completor': function('vimcomplete#buffer#Completor')}
```

I don't know vim9script at all, but by trial and error method  I came to the conclusion that the problem is probably this line:
  ` if !getscriptinfo({ name: $'vimcomplete/autoload/vimcomplete/{key}' })->empty()`
I experimented with using relative paths, $HOME, etc. but ended up with:
```
for [key, newopts] in opts->items()
	var filepath = printf('f:/users/ro/vimfiles/plugged/vimcomplete/autoload/vimcomplete/%s.vim', key)
  	if filereadable(filepath )
	    var o = eval($'{key}.options')
        o->extend(newopts)
			#echom "newopts: " newopts
        #else
          #  echom "Skript nebyl načten: "  filepath
        endif
    endfor   
```

Then VimCompleteCompletors showed me:
![image](https://github.com/user-attachments/assets/cd4d480c-15af-485c-874f-cf4305315b70)

**Comment by girishji** [comment]
I will look into this soon

**Comment by girishji** [comment]
Please try now.

**Comment by arozehnal** [comment]
I think the fix worked correctly.  :-)
I uninstalled the original version of the plugin, then reinstalled the plugin.
Immediately after installation the status is the same with the previous version.
![compl1](https://github.com/user-attachments/assets/dc2d6f01-dcf6-4bed-ab92-a5347f8c7482)

However, after ccompleting other completion sources,  VimCompleteCompletors showed me:
![compl2](https://github.com/user-attachments/assets/4d011729-100c-45d6-96ca-d2c9c6e67012)


I am satisfied, the issue can be closed.
Thank you for a great plugin..
