### ISSUE TITLE
Be nice when defining Tab and S-Tab

### ISSUE THREAD

**Issue by pusewicz** [girishji/vimcomplete#80]
When defining the mappings, it would be nice to modify the mapping so that it does not remove the currently defined mappings in possible, similarly to how endwise handles it:

https://github.com/tpope/vim-endwise/blob/master/plugin/endwise.vim#L134-L151

**Comment by girishji** [comment]
Interesting. You want to do something with `<tab>` ahead of what this plugin does? What use-case would that be?

**Comment by girishji** [comment]
There's another bug:
```
let rhs = substitute(get(map, 'rhs', ''), '\c<sid>', '<SNR>' . get(map, 'sid') . '_', 'g')
```
In vim9script there is no need for `<sid>` since functions are executed in the context of the script they are defined in. <sid> is optional. Both of these are valid:
```
inoremap <expr> <Tab>   OnWhitespace() ? "\<tab>" : "\<c-n>"
inoremap <expr> <Tab>   <SID>OnWhitespace() ? "\<tab>" : "\<c-n>"
```
However, when you transport the rhs to another script there is need to replace <sid> with <snr>. Since <sid> is optional the above `substitute()` will not work. When keybinding is executed it complains that `OnWhitespace()` is undefined.

**Comment by girishji** [comment]
Please try now. I've made `<tab>` easy to integrate with other plugins.

README.md:

## Tab Completion

You can map the `<Tab>` and `<S-Tab>` keys to navigate autocomplete items in insert mode. By default, Vim uses `CTRL-N` and `CTRL-P` to cycle through completion menu options.

To enable `<Tab>` and `<S-Tab>` for this purpose, add the following to your configuration:

```vim
vim9script
let g:vimcomplete_tab_enable = 1
```

> **Note**: Enabling this option will remove any existing mappings for `<Tab>` and `<S-Tab>`.

If you'd like to retain `<Tab>` and `<S-Tab>` mappings from other plugins, unset the above variable and instead use these custom mappings, substituting `{rhs}` as needed (using `"\<Tab>"` as `"{rhs}"` will behave the same as setting the variable):

```vim
inoremap <buffer><expr> <tab>   g:VimCompleteTab() ?? "{rhs}"
inoremap <buffer><expr> <s-tab> g:VimCompleteSTab() ?? "{rhs}"
```

This configuration allows `<Tab>` and `<S-Tab>` to integrate with other plugin mappings.

**Comment by pusewicz** [comment]
> When keybinding is executed it complains that OnWhitespace() is undefined.

Maybe that's why those should be defined as mappings, too? Like in endwise:

https://github.com/tpope/vim-endwise/blob/master/plugin/endwise.vim#L130-L132
